"""Per-workspace runtime enforcement state.

Each workspace gets its own SQLite file. This is the strongest tenant
isolation available: not a WHERE clause that a future query could forget, but
a separate database file that another tenant's code path never opens.

Proven in the Phase 0 audit (docs/saas/SAAS_ARCHITECTURE_AUDIT.md section 4,
probe 2): tenant A exhausting its daily quota leaves tenant B untouched, and
A's approval token presented against B's store is denied "approval not found".
"""

from __future__ import annotations

import re
from pathlib import Path

from kynd_runtime import SqliteStore

from ..config import get_settings

# Workspace ids are generated by `new_id("ws")` and are always
# `ws_<32 hex chars>`. This is validated before the id is ever used to build a
# filesystem path, so a crafted id can never traverse out of the state
# directory. Defence in depth: the id also comes from a membership row the
# server looked up, never from client input.
_WORKSPACE_ID = re.compile(r"^ws_[0-9a-f]{32}$")


class InvalidWorkspaceId(ValueError):
    """Raised when a workspace id is not the exact expected shape."""


def store_path(workspace_id: str) -> Path:
    """The SQLite path for a workspace. Validates the id shape first."""
    if not _WORKSPACE_ID.match(workspace_id):
        raise InvalidWorkspaceId(
            f"Refusing to build a filesystem path from a malformed workspace id: "
            f"{workspace_id!r}"
        )
    base = Path(get_settings().runtime_state_dir).resolve()
    path = (base / f"{workspace_id}.db").resolve()

    # Belt and braces. The regex above already makes traversal impossible; this
    # asserts the invariant the regex is protecting rather than trusting that a
    # future edit to the regex preserves it.
    if base not in path.parents:
        raise InvalidWorkspaceId(
            f"Resolved store path escapes the runtime state directory: {path}"
        )
    return path


def get_store(workspace_id: str) -> SqliteStore:
    """Open (creating if needed) the runtime store for one workspace.

    Cheap: the Phase 0 audit measured the full
    Constitution+Registry+Store+Executor construction at 0.601 ms, so this is
    built per request rather than cached. A cache here would need invalidating
    every time a customer edited their governance rules, and a stale
    constitution enforcing yesterday's rules is a worse failure than 0.6 ms.
    """
    path = store_path(workspace_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    return SqliteStore(path)
