"""ai_proposals

Revision ID: 61d3f32902b8
Revises: 85291f408b58
Create Date: 2026-09-01 17:36:55.823862
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61d3f32902b8'
down_revision: Union[str, None] = '85291f408b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_proposals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('capability', sa.String(length=128), nullable=True),
    sa.Column('action_type', sa.String(length=128), nullable=True),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('REJECTED', 'ROUTED_TO_APPROVAL', name='ai_proposal_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approval_request_id', sa.String(length=64), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_proposals_created_at'), 'ai_proposals', ['created_at'], unique=False)
    op.create_index('ix_ai_proposals_workspace_created', 'ai_proposals', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_proposals_workspace_id'), 'ai_proposals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_proposals_workspace_id'), table_name='ai_proposals')
    op.drop_index('ix_ai_proposals_workspace_created', table_name='ai_proposals')
    op.drop_index(op.f('ix_ai_proposals_created_at'), table_name='ai_proposals')
    op.drop_table('ai_proposals')
    # ### end Alembic commands ###
