"""audit_events

Revision ID: 652aa4c821af
Revises: 895e6864d5f0
Create Date: 2026-09-01 17:16:27.162320
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '652aa4c821af'
down_revision: Union[str, None] = '895e6864d5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.Enum('GOVERNANCE_RULE_CREATED', 'GOVERNANCE_RULE_UPDATED', 'GOVERNANCE_RULE_DELETED', 'CAPABILITY_CREATED', 'CAPABILITY_UPDATED', 'CAPABILITY_DELETED', 'APPROVAL_REQUESTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'WORKSPACE_UPDATED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED', name='audit_event_type'), nullable=False),
    sa.Column('outcome', sa.Enum('SUCCESS', 'DENIED', 'ERROR', name='audit_outcome'), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('runtime_execution_id', sa.Integer(), nullable=True),
    sa.Column('approval_request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_workspace_created', 'audit_events', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_audit_events_workspace_resource', 'audit_events', ['workspace_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_events_workspace_type', 'audit_events', ['workspace_id', 'event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_workspace_type', table_name='audit_events')
    op.drop_index('ix_audit_events_workspace_resource', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_workspace_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
