"""governance: integrations, rules, workspace capabilities

Revision ID: f13737f69fa3
Revises: d6d1c3ccef0c
Create Date: 2026-09-01 16:44:58.541285
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f13737f69fa3'
down_revision: Union[str, None] = 'd6d1c3ccef0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_governance_rules_workspace_enabled', 'governance_rules', ['workspace_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_governance_rules_workspace_id'), 'governance_rules', ['workspace_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.Enum('SLACK', 'EMAIL', name='integration_provider'), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='integration_status'), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('credential_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('credential_key_id', sa.String(length=64), nullable=True),
    sa.Column('credential_hint', sa.String(length=64), nullable=True),
    sa.Column('connected_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider', name='uq_integration_workspace_provider')
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('workspace_capabilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('integration_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('max_calls_per_day', sa.Integer(), nullable=True),
    sa.Column('allowed_targets', sa.JSON(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_capability_workspace_name')
    )
    op.create_index(op.f('ix_workspace_capabilities_integration_id'), 'workspace_capabilities', ['integration_id'], unique=False)
    op.create_index(op.f('ix_workspace_capabilities_workspace_id'), 'workspace_capabilities', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_capabilities_workspace_id'), table_name='workspace_capabilities')
    op.drop_index(op.f('ix_workspace_capabilities_integration_id'), table_name='workspace_capabilities')
    op.drop_table('workspace_capabilities')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_governance_rules_workspace_id'), table_name='governance_rules')
    op.drop_index('ix_governance_rules_workspace_enabled', table_name='governance_rules')
    op.drop_table('governance_rules')
    # ### end Alembic commands ###
